### ISSUE TITLE
How to convert into CAMI Bioboxes format?

### ISSUE THREAD

**Issue by eparisis** [CAMI-challenge/OPAL#53]
Hi there. I am not sure how to convert my taxonomic profile into the CAMI Bioboxes Format. Suppose I run 2 different tools for taxonomic binning and convert the results into a simple OTU Table. Am I supposed to write a script manually to convert this into CAMI format? 

Are there any scripts available to convert basic taxonomic profilers' outputs into CAMI Format? 

I really appreciate any help you can provide.

**Comment by fernandomeyer** [comment]
Hi, we don't officially provide conversion scripts because we can't keep up with tools producing each a different format, and some tools like MetaPhlAn nowadays already support the CAMI Bioboxes format. However, we created Bioboxes in the past including conversion scripts that might be helpful at https://github.com/CAMI-challenge/docker_profiling_tools

Example converting Bracken output to the CAMI Bioboxes format: https://github.com/CAMI-challenge/docker_profiling_tools/blob/master/bracken/convert_bracken.py
It uses NCBI taxdump files.

I hope this helps.

**Comment by eparisis** [comment]
I am actually trying to implement this for kraken2 as a start but what I do is, convert the kraken2 output into Biom and extract from there the OTU Table (which is also very nice to use in Phyloseq - R). I'm probably going to output workflows from other tools in the same format.

Thanks a lot, I will have a look into those scripts you mentioned.
