### ISSUE TITLE
Labels in Spider plots are incorrect color

### ISSUE THREAD

**Issue by Tiam-F** [CAMI-challenge/OPAL#54]
I observed that the labels for completeness, purity, l1 norm error and Unifrac have the wrong color compared to the Spider plot. 
For example, the green and pink color in the plot is not present in the labels. Is this something anyone have encountered? 

![spider_plot_relative](https://user-images.githubusercontent.com/94529693/224730583-90c9e9ca-9ca0-428a-ad2d-1d23e1c97f85.png)

I´m using the default settings and version 1.011.

**Comment by fernandomeyer** [comment]
Thanks for reporting this. I found that the labels became incorrect with some version of matplotlib > 3.2.1, due to some change or maybe a bug in matplotlib. They were correct with matplotlib==3.2.1, which was the version recommended for OPAL 1.0.11.
Anyway, I updated OPAL's requirements and released now OPAL 1.0.12 with a [workaround](https://github.com/CAMI-challenge/OPAL/blob/28975f909c8ae00b29ccc9cf7877cea64c6cb00d/cami_opal/plots.py#L414) to display the correct labels.
